branches:
  only:
    - master
    - development

matrix:
  include:
    # Android Build
    - language: android
      dist: trusty
      sudo: required
      jdk: oraclejdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.android/build-cache
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_install:
        - nvm install 10
        - .travis/before_install.sh
        - echo yes | sdkmanager "platforms;android-26"
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - tools
      env: LANE='android'
      script: .travis/run.sh

      # iOS Build
    - language: objective-c
      os: osx
      osx_image: xcode9.4
      node_js: 10
      cache:
        - bundler
        - pip
      before_install:
        - nvm install 10
        - .travis/before_install.sh
      env: LANE='ios'
      script: .travis/run.sh

before_deploy:
  - ls -la ${TRAVIS_BUILD_DIR}/android/app/build/outputs/apk || true
  - ls -la ${TRAVIS_BUILD_DIR}/android/app/build/outputs/apk/release || true

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file: ${TRAVIS_BUILD_DIR}/android/app/build/outputs/apk/release/app-release-unsigned.apk
    kip_cleanup: true
    draft: true
    on:
      condition: $LANE = 'android'
  - provider: releases
    api_key: $GH_TOKEN
    file: ${TRAVIS_BUILD_DIR}/ios/build/Build/Products/Release-iphonesimulator/helloTravis.app
    kip_cleanup: true
    draft: true
    on:
      condition: $LANE = 'ios'
